I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 66, in script
    dedektif "Gerçekler her ne ise eninde sonunda ortaya çıkacaktır."
Exception: Sayer 'dedektif' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 66, in script
    dedektif "Gerçekler her ne ise eninde sonunda ortaya çıkacaktır."
  File "C:\Users\Beyza\Downloads\renpy-8.3.7-sdk\renpy\ast.py", line 2586, in execute
    Say.execute(self)
  File "C:\Users\Beyza\Downloads\renpy-8.3.7-sdk\renpy\ast.py", line 583, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Beyza\Downloads\renpy-8.3.7-sdk\renpy\ast.py", line 472, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'dedektif' is not defined.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
Gizemli Vaka 1.0
Fri May 16 20:40:37 2025
